services:
  - type: web
    name: stockpulse-ai
    env: python
    plan: free
    rootDirectory: mod_bot
    buildCommand: pip install -r requirements.txt && python init_db.py && python train_and_save.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
    databases:
      - name: stockpulse-db
        databaseName: stockpulse
        user: stockpulse_user

databases:
  - name: stockpulse-db
    databaseName: stockpulse
    user: stockpulse_user
    plan: free


